version: "3"

services:
  tailscale-derp:
    container_name: tailscale-derp
    image: tailscale-derp-docker:1.0
    hostname: derp.example.com
    volumes:
      - /lib/modules:/lib/modules:ro
      - $PWD/certs:/root/derper/derp.example.com
      - $PWD/config:/var/lib/tailscale
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TAILSCALE_DERP_HOSTNAME=derp.example.com
      - TAILSCALE_DERP_VERIFY_CLIENTS=true
      - TAILSCALE_DERP_CERTMODE=letsencrypt
      - TAILSCALE_LOGIN_SERVER=headscale.example.com
      - TAILSCALE_AUTH_KEY=<your_tailscale_auth_key>
      - TAILSCALE_DERP_ADDR=":443"
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 3478:3478/udp
      #Uncomment only if you aren't running tailscaled on the host system otherwise it will error
      #- 41641:41641/udp
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun
